## Webdriver
WEBDRIVER_EXECUTABLE_PATH = ""

## Login
LOGIN_REQUIRED = False
LOGIN_URL = ""
USERNAME = ""
PASSWORD = ""

## Base urls
JOB_BASE_URL = ""
RESUME_BASE_URL = ""

## Results
# Pagination
MAX_PAGINATION_WITHOUT_LOGIN = 20
MAX_PAGINATION_WITH_LOGIN = 20
# Result per page
MAX_RESULTS_PER_JOB_PAGE = 10
MAX_RESULTS_PER_RESUME_PAGE = 50
# Total results
MAX_RESULTS_FOR_JOB_IN_LOGIN_STATE = (MAX_PAGINATION_WITH_LOGIN * MAX_RESULTS_PER_JOB_PAGE)
MAX_RESULTS_FOR_RESUME_IN_LOGIN_STATE = (MAX_PAGINATION_WITH_LOGIN * MAX_RESULTS_PER_RESUME_PAGE)
MAX_RESULTS_FOR_JOB_OUTSIDE_LOGIN_STATE = (MAX_PAGINATION_WITHOUT_LOGIN * MAX_RESULTS_PER_JOB_PAGE)
MAX_RESULTS_FOR_RESUME_OUTSIDE_LOGIN_STATE = (MAX_PAGINATION_WITHOUT_LOGIN * MAX_RESULTS_PER_RESUME_PAGE)
